import { Avatar, Box, Button, Card, CardContent, CardHeader, Container, Grid, Link, Stack, Typography, AppBar, Toolbar, CssBaseline } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import './App.css';

function Landing() {
  const navigate = useNavigate();

  const handleSignIn = async () => {
    try {
      const response = await fetch('http://localhost:3000/a');  
      const data = await response.text();
  
      if (data.trim() === 'Logged in') {
        navigate('/dcode');  
      } else {
        navigate('/login');  
        window.location.reload();
        navigate('/dcode');
      }
    } catch (error) {
      console.error('Error checking login status:', error);
      navigate('/login');  
      window.location.reload(); 
      navigate('/dcode')
    }
  };

  // Sample testimonials are generated by ChatGPT
  const userTestimonials = [
    {
      testimonial: "dCode has revolutionized how I understand and analyze code. It's an invaluable tool for any aspiring coder.",
      name: "Emily Brown",
      occupation: "Computer Science Student",
      avatar: <Avatar sx={{ bgcolor: 'blue' }}></Avatar>  
    },
    {
      testimonial: "Using dCode, I've seen a marked improvement in my ability to decipher complex code. Highly recommended!",
      name: "David Lee",
      occupation: "Junior Developer",
      avatar: <Avatar sx={{ bgcolor: 'yellow' }}></Avatar>   
    },
    {
      testimonial: "As an educator, dCode has been instrumental in helping my students grasp code comprehension concepts effectively.",
      name: "Sarah Rodriguez",
      occupation: "Programming Instructor",
      avatar: <Avatar sx={{ bgcolor: 'purple' }}></Avatar>  
    },
  ];

  return (
    <div>
      <CssBaseline />
      <AppBar sx={{ width: '100%', justifyContent: 'center' }}>
        <Toolbar sx={{ display: 'flex', alignItems: 'center' }}>
          <Typography
            variant="h4"
            component="div"
            sx={{
              flexGrow: 1,
              paddingTop: 1,
              fontWeight: 'bold',
              fontSize: '3.5rem',
              textTransform: 'uppercase',
              letterSpacing: '0.7rem',
              color: '#FFFFFF',
              textShadow: '3px 3px 3px rgba(0, 0, 0, 0.3)',
              marginTop: 'auto',
              marginBottom: 'auto',  
            }}
          >
            dCode
          </Typography>
        </Toolbar>
      </AppBar>
       {/* Code below adapted from MUI's free landing page templates https://github.com/mui/material-ui/blob/v5.16.0/docs/data/material/getting-started/templates/landing-page/ */}
      <Container
        sx={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          pt: { xs: 14, sm: 20 },
          pb: { xs: 8, sm: 12 },
        }}
      >
        <Stack spacing={2} useFlexGap sx={{ width: { xs: '100%', sm: '70%' } }}>
          <Typography
            variant="h2"
            sx={{
              display: 'flex',
              flexDirection: { xs: 'column', md: 'row' },
              alignSelf: 'center',
              textAlign: 'center',
              fontSize: 'clamp(2.5rem, 8vw, 3rem)',
              fontWeight: 'bold',
              marginTop: '-2.5rem',  
            }}
          >
            From Code to&nbsp;
            <Typography
              component="span"
              variant="h2"
              sx={{
                fontSize: 'clamp(2rem, 8vw, 3rem)',
                color: (theme) => (theme.palette.mode === 'light' ? 'primary.main' : 'primary.light'),
                fontWeight: 'bold',
              }}
            >
              Clarity
            </Typography>
          </Typography>
          <Typography
            textAlign="center"
            color="text.secondary"
            sx={{ alignSelf: 'center', width: { sm: '100%', md: '80%' } }}
          >
            Get started with AI-powered code comprehension for students and educators. Explore code samples that start at your skill level and help strengthen your code analysis and reading skills.
          </Typography>
          <Stack
            direction={{ xs: 'column', sm: 'row' }}
            alignSelf="center"
            spacing={1}
            useFlexGap
            sx={{ pt: 2, width: { xs: '100%', sm: 'auto' } }}
          >
            <Button variant="contained" color="primary" onClick={handleSignIn}>
              Get Started
            </Button>
          </Stack>
          <Typography variant="caption" textAlign="center" sx={{ opacity: 0.8 }}>
            By clicking &quot;Get Started&quot; you agree to our&nbsp;
            <Link href="#" color="primary">
              Terms & Conditions
            </Link>
            .
          </Typography>
          <Box
            component="img"
            src="/dcode-landing.png"
            alt="dCode Landing"
            sx={{
              width: '100%',
              maxWidth: '600px',
              alignSelf: 'center',
            }}
          />
        </Stack>
      </Container>
      <Container
        id="testimonials"
        sx={{
          pb: { xs: 8, sm: 16 },
          position: 'relative',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: { xs: 3, sm: 6 },
        }}
      >
        <Box
          sx={{
            width: { sm: '100%', md: '60%' },
            textAlign: { sm: 'left', md: 'center' },
          }}
        >
          <Typography component="h2" variant="h4" color="text.primary" marginTop="-3rem">
            Testimonials
          </Typography>
          <Typography variant="body1" color="text.secondary">
            See what real students and educators say about dCode.
          </Typography>
        </Box>
        <Grid container spacing={2}>
          {userTestimonials.map((testimonial, index) => (
            <Grid item xs={12} sm={6} md={4} key={index} sx={{ display: 'flex' }}>
              <Card
                sx={{
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                  flexGrow: 1,
                  p: 1,
                }}
              >
                <CardContent>
                  <Typography variant="body2" color="text.secondary">
                    {testimonial.testimonial}
                  </Typography>
                </CardContent>
                <Box
                  sx={{
                    display: 'flex',
                    flexDirection: 'row',
                    justifyContent: 'space-between',
                    pr: 2,
                  }}
                >
                  <CardHeader
                    avatar={testimonial.avatar}
                    title={testimonial.name}
                    subheader={testimonial.occupation}
                  />
                </Box>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Container>
      <Box component="footer" sx={{ py: 2, backgroundColor: 'primary.main', color: 'white', position: 'absolute', left: 0, width: '100%' }}>
        <Container maxWidth="lg">
        <Typography variant="body2" color="white" align="center">
            {'Copyright © '}
            <Link color="inherit" href="/">
              dCode
            </Link>{' '}
            {new Date().getFullYear()}
            {'.'}
          </Typography>
        </Container>
      </Box>
    </div>
  );
}

export default Landing;
